//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Actief
{
	private bool actief
	{
		get;
		set;
	}

	private Array dagen
	{
		private get;
		private set;
	}

	private DateTime uurVanaf
	{
		get;
		set;
	}

	private DateTime uurTot
	{
		get;
		set;
	}

	public virtual Capcode Capcode
	{
		get;
		set;
	}

}

