//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Beheerder
{
	private string naam
	{
		get;
		set;
	}

	private string wachtwoord
	{
		get;
		set;
	}

	public virtual void opgaveBeschikbaarheidPiket()
	{
		throw new System.NotImplementedException();
	}

	public virtual void opvragenSMSnummerHoveelheid()
	{
		throw new System.NotImplementedException();
	}

}

