//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <remarks>Retour SMS en App bericht: beschikbaarheid Piket functionaris. smsNr is 4 cijferig afkomstig van verstuurd bericht.</remarks>
public enum Beschikbaar : int
{
	vertraagd,
	beschikbaar,
	niet_beschikbaar
};
