//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Capcode
{
	private int capcodeNr
	{
		get;
		set;
	}

	private string omschrijving
	{
		get;
		set;
	}

	public virtual OproepFunctie OproepFunctie
	{
		get;
		set;
	}

}

