//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Kazerne
{
	private string naam
	{
		get;
		set;
	}

	private string wachtwoord
	{
		get;
		set;
	}

	private dateTime geldigVanaf
	{
		get;
		set;
	}

	private dateTime geldigTot
	{
		get;
		set;
	}

	private bool uitgeschakeld
	{
		get;
		set;
	}

	public virtual OproepMelding OproepMelding
	{
		get;
		set;
	}

}

