//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class OproepMelding
{
	private dateTime activering
	{
		get;
		set;
	}

	private dateTime gesloten
	{
		get;
		set;
	}

	private int smsNr
	{
		get;
		set;
	}

	private string bericht
	{
		get;
		set;
	}

	private string capcode
	{
		get;
		set;
	}

	private string oproepFunctie
	{
		get;
		set;
	}

	public virtual IEnumerable<SMS> SMS
	{
		get;
		set;
	}

	public virtual TextToSpeech TextToSpeech
	{
		get;
		set;
	}

	public virtual IEnumerable<VerstuurdeBerichtenLog> VerstuurdeBerichtenLog
	{
		get;
		set;
	}

	public virtual void verstuurBerichten()
	{
		throw new System.NotImplementedException();
	}

	public virtual void berichtenLog()
	{
		throw new System.NotImplementedException();
	}

}

