//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <remarks>
/// Interface en Oproep is
///  in een service verwerkt.
/// </remarks>
public class Oproep
{
	private object regio
	{
		get;
		set;
	}

	private object discipline
	{
		get;
		set;
	}

	private object omschrijving
	{
		get;
		set;
	}

	private object korps
	{
		get;
		set;
	}

	private string capcode
	{
		get;
		set;
	}

	public virtual OproepFunctie OproepFunctie
	{
		get;
		set;
	}

	public virtual bool actieveOproep()
	{
		throw new System.NotImplementedException();
	}

}

