//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <remarks>
/// Interface en Oproep is in een service verwerkt.
/// </remarks>

public class Oproep
{
    public string regio;
	public string discipline;
    public string capcode;

    public void creeerOproep(string _capcode)
	{
        regio        = _capcode.Substring(0, 2);
        capcode      = _capcode;
	}

    public string getRegio()
    {
        return regio;
    }

    public string getOproepCapcode()
    {
        return capcode;
    }
}
