//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <remarks>
/// Interface en Oproep is
///  in een service verwerkt.
/// </remarks>
public interface P2000 
{
	string capcode { get;set; }

	Oproep Oproep { get;set; }

	string bewaarBericht();

}

