//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class PiketFunctionaris
{
	private object naam
	{
		get;
		set;
	}

	private object functie
	{
		get;
		set;
	}

	private Beschikbaar beschikbaar
	{
		get;
		set;
	}

	private string wachtwoord
	{
		get;
		set;
	}

	private int incidentBeheerder
	{
		get;
		set;
	}

	private bool kazerneBeheerder
	{
		get;
		set;
	}

	private bool actief
	{
		get;
		set;
	}

	private string kazerne
	{
		get;
		set;
	}

	public virtual OproepMelding OproepMelding
	{
		get;
		set;
	}

	public virtual IEnumerable<TelefoonNummer> TelefoonNummer
	{
		get;
		set;
	}

}

