//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class PiketFunctionaris
{
	private string naam
	{
		get;
		set;
	}

	private string functie
	{
		get;
		set;
	}

	private bool beschikbaar
	{
		get;
		set;
	}

	private string wachtwoord
	{
		get;
		set;
	}

	private int incidentBeheerder { get; set; }

	private bool locatieBeheerder { get; set; }

	private bool actief 	{ get; set; }

	private string locatie
	{
		get;
		set;
	}

	private bool gebruikSms
	{
		get;
		set;
	}

	private bool gebruikEmail
	{
		get;
		set;
	}

	public virtual IEnumerable<OproepFunctie> OproepFunctie
	{
		get;
		set;
	}

	public virtual void geefEmailAccount()
	{
		throw new System.NotImplementedException();
	}

	public virtual void geefTelefoonnummer()
	{
		throw new System.NotImplementedException();
	}

    public virtual void setPiketFunctionaris(bool _actief, bool _gebruikSMS, bool _beschikbaar, string _naam)
    {
        actief = _actief;
        gebruikSms = _gebruikSMS;
        beschikbaar = _beschikbaar;
        naam = _naam;
    }

    public bool getActief()
    {
        return actief;
    }

    public bool getBeschikbaar()
    {
        return beschikbaar;
    }
}

