//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Regio
{
	private string regio;

    public void setRegio(string _regio)
    {
        regio = _regio;
    }

    public string getRegio()
    {
        return regio;
    }


	public virtual OproepFunctie OproepFunctie
	{
		get;
		set;
	}

}

