//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class OproepMelding
{
	private DateTime activering
	{
		get;
		set;
	}

	private DateTime gesloten
	{
		get;
		set;
	}

	private int smsNr
	{
		get;
		set;
	}

	private string bericht
	{
		get;
		set;
	}

	private string capcode
	{
		get;
		set;
	}

	private ArrayClass oproepFunctie
	{
		get;
		set;
	}

	public virtual IEnumerable<SMS> SMS
	{
		get;
		set;
	}

	public virtual IEnumerable<TextToSpeech> TextToSpeech
	{
		get;
		set;
	}

	public virtual IEnumerable<Email> Email
	{
		get;
		set;
	}

	/// <summary>
	/// OproepMelding
	/// </summary>
	public virtual App App
	{
		get;
		set;
	}

	public virtual void verstuurBericht(object interface)
	{
		throw new System.NotImplementedException();
	}

	public virtual void berichtenLog()
	{
		throw new System.NotImplementedException();
	}

	public virtual void geefLocatie()
	{
		throw new System.NotImplementedException();
	}

}

