//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class OproepFunctie
{
	private bool actief
	{
		get;
		set;
	}

	private string activeringsMelding
	{
		get;
		set;
	}

	private string berichtActieveGebruiker
	{
		get;
		set;
	}

	private string berichtDeactieveGebruiker
	{
		get;
		set;
	}

	private int capcodeNr
	{
		get;
		set;
	}

	private string deactiveringsMelding
	{
		get;
		set;
	}

	private string totaalAantalPersonenEmail
	{
		get;
		set;
	}

	private int totaalAantalPersonenSms
	{
		get;
		set;
	}

	private int totaalAantalPersonen
	{
		get;
		set;
	}

	public virtual OproepMelding OproepMelding
	{
		get;
		set;
	}

	public virtual bool activeerOproepFunctie()
	{
		throw new System.NotImplementedException();
	}

	public virtual bool dezeRegio(object regio)
	{
		throw new System.NotImplementedException();
	}

	public virtual void geefPiketFunctionaris()
	{
		throw new System.NotImplementedException();
	}

	public virtual void capcodeAanwezig()
	{
		throw new System.NotImplementedException();
	}

}

